######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 14 23:05:30 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += SymbolNameMap.h
SOURCES += main.cpp SymbolNameMap.cpp
